### ISSUE TITLE
Running n8n in Docker and it's not working

### ISSUE THREAD

**Issue by MariuszT** [CodoBee/CodoBee#10]
I have this simple example:

```
docker volume create n8n_data
docker run -it -d --rm --name n8n -p 5678:5678 -e N8N_SECURE_COOKIE="false" -v n8n_data:/home/node/.n8n docker.n8n.io/n8nio/n8n
```

At startup I want to register admin account and it's not working when I'm trying by CodoBee tunnel. The same directly in Docker works perfect.

**Comment by lukaszlach** [comment]
What is this task about? Me installing n8n and debugging why it does not work or what?

**Comment by MariuszT** [comment]
It's fixed! The problem was that POST data was being lost. The method we used to solve it means that we no longer expect this type of problem in the future.
